# Generated by Django 4.2.6 on 2023-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=15)),
                ('ifu', models.IntegerField()),
                ('categorie', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=300)),
            ],
        ),
    ]
