# Generated by Django 4.2.6 on 2023-11-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestionnaire.contact')),
            ],
            bases=('gestionnaire.contact',),
        ),
        migrations.CreateModel(
            name='GroupeTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du Groupe de Taxes')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255, verbose_name='Libellé')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité en Stock')),
                ('cout_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Coût d'Achat")),
                ('niveau_alerte_stock', models.PositiveIntegerField(verbose_name="Niveau d'Alerte de Stock")),
                ('unite_mesure', models.CharField(max_length=50, verbose_name='Unité de Mesure')),
                ('date_ajout', models.DateField(auto_now_add=True, verbose_name="Date d'Ajout")),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de Péremption')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produit_images/', verbose_name='Image du Produit')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.familleproduit', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.fournisseur', verbose_name='Fournisseur')),
                ('groupe_taxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.groupetaxe', verbose_name='Groupe de Taxes')),
            ],
            options={
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
