# Generated by Django 4.2.6 on 2023-11-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0002_familleproduit_fournisseur_groupetaxe_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.contact', verbose_name='Fournisseur'),
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
