# Generated by Django 4.2.6 on 2023-11-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0003_alter_produit_fournisseur_delete_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familleproduit',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la Famille'),
        ),
    ]
