# Generated by Django 4.2.6 on 2023-11-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0004_alter_familleproduit_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='famille',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='groupe_taxe',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FamilleProduit',
        ),
        migrations.DeleteModel(
            name='GroupeTaxe',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
