# Generated by Django 4.2.6 on 2023-11-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100, verbose_name='Famille')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100)),
                ('taux', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_fiscal', models.CharField(blank=True, max_length=20, null=True)),
                ('exoneration', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('attente', 'En attente')], default='actif', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100, verbose_name="Libéllé de l'unité de mesure")),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('cout_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('niveau_alerte_stock', models.PositiveIntegerField()),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de creation')),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produit_images/')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.familleproduit')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
                ('groupe_taxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.groupetaxe')),
                ('unite_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.unitemesure')),
            ],
        ),
    ]
