# Generated by Django 4.2.6 on 2023-12-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0003_alter_contact_categorie_alter_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(verbose_name='Date de Commande')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('livree', 'Livré'), ('annulee', 'Annulée')], default='En cours', max_length=20, verbose_name='Statut de la Commande')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date de Réception')),
                ('client', models.ForeignKey(limit_choices_to={'categorie': 'Client'}, on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Client')),
            ],
            options={
                'verbose_name_plural': 'Commandes Clients',
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('en_cours', 'En Cours'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='En cours', max_length=20, verbose_name='Statut de la Commande')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('date_reception', models.DateField(blank=True, null=True, verbose_name='Date de Réception')),
                ('fournisseur', models.ForeignKey(limit_choices_to={'categorie': 'Fournisseur'}, on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name_plural': 'Commandes Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='FamilleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100, verbose_name='Libéllé de la famille de Produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Familles de Produit',
            },
        ),
        migrations.CreateModel(
            name='GroupeTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100, verbose_name='Libéllé du Groupe de Taxe')),
                ('taux', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux de Taxe')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('code_fiscal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Fiscal')),
                ('exoneration', models.BooleanField(default=False, verbose_name='Exonéré')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('attente', 'En attente')], default='actif', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name_plural': 'Groupes de Taxes',
            },
        ),
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100, verbose_name="Libéllé de l'unité de mesure")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Unites de Mesure',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=255, verbose_name='Libellé')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité en Stock')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Coût d'Achat")),
                ('niveau_alerte_stock', models.PositiveIntegerField(verbose_name="Niveau d'Alerte de Stock")),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de Péremption')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gestionnaire/imgs/', verbose_name='Image du Produit')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.familleproduit', verbose_name='Famille')),
                ('groupe_taxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.groupetaxe', verbose_name='Groupe de Taxes')),
                ('unite_mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.unitemesure', verbose_name='Unité de Mesure')),
            ],
            options={
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('commande_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.commandeclient', verbose_name='Commande Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name_plural': 'Lignes de commande client',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Unitaire')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.commandefournisseur', verbose_name='Commande Fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name_plural': 'Lignes de Commande',
            },
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='produits',
            field=models.ManyToManyField(through='gstock.LigneCommande', to='gstock.produit', verbose_name='Produits'),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='produits',
            field=models.ManyToManyField(through='gstock.LigneCommandeClient', to='gstock.produit', verbose_name='Produits'),
        ),
    ]
