# Generated by Django 4.2.6 on 2023-11-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('gstock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familleproduit',
            options={'verbose_name_plural': 'Familles de Produits'},
        ),
        migrations.AlterModelOptions(
            name='groupetaxe',
            options={'verbose_name_plural': 'Groupes de Taxes'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterField(
            model_name='familleproduit',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='familleproduit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='familleproduit',
            name='libele',
            field=models.CharField(max_length=100, verbose_name='Libéllé de la famille de Produit'),
        ),
        migrations.AlterField(
            model_name='groupetaxe',
            name='code_fiscal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Fiscal'),
        ),
        migrations.AlterField(
            model_name='groupetaxe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='groupetaxe',
            name='exoneration',
            field=models.BooleanField(default=False, verbose_name='Exonéré'),
        ),
        migrations.AlterField(
            model_name='groupetaxe',
            name='libele',
            field=models.CharField(max_length=100, verbose_name='Libéllé du Groupe de Taxe'),
        ),
        migrations.AlterField(
            model_name='groupetaxe',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('attente', 'En attente')], default='actif', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='groupetaxe',
            name='taux',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux de Taxe'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='cout_achat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Coût d'Achat"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_peremption',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Péremption'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.familleproduit', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='groupe_taxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.groupetaxe', verbose_name='Groupe de Taxes'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produit_images/', verbose_name='Image du Produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='libele',
            field=models.CharField(max_length=255, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='niveau_alerte_stock',
            field=models.PositiveIntegerField(verbose_name="Niveau d'Alerte de Stock"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(verbose_name='Quantité en Stock'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite_mesure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.unitemesure', verbose_name='Unité de Mesure'),
        ),
        migrations.AlterField(
            model_name='unitemesure',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
