# Generated by Django 4.2.6 on 2023-12-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familleproduit',
            name='code',
            field=models.CharField(default=1, max_length=100, verbose_name='code'),
            preserve_default=False,
        ),
    ]
