# Generated by Django 4.2.6 on 2023-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstock', '0002_alter_familleproduit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familleproduit',
            options={'verbose_name_plural': 'Familles de Produit'},
        ),
        migrations.AlterModelOptions(
            name='unitemesure',
            options={'verbose_name_plural': 'Unites de Mesure'},
        ),
        migrations.AlterField(
            model_name='familleproduit',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
