# Generated by Django 4.2.6 on 2023-12-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gstock', '0002_familleproduit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gstock.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité'),
        ),
    ]
