# Generated by Django 4.2.6 on 2023-12-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstock', '0003_alter_lignecommande_montant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefournisseur',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Montant'),
        ),
    ]
