# Generated by Django 4.2.6 on 2023-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstock', '0003_alter_familleproduit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gestionnaire/imgs/', verbose_name='Image du Produit'),
        ),
    ]
