# Generated by Django 4.2.6 on 2023-12-19 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gstock', '0004_commandefournisseur_montant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecommande',
            options={'verbose_name_plural': 'Lignes de Commande fournisseur'},
        ),
        migrations.AlterModelOptions(
            name='lignecommandeclient',
            options={'verbose_name_plural': 'Lignes de Commande client'},
        ),
        migrations.RenameField(
            model_name='lignecommandeclient',
            old_name='commande_client',
            new_name='commande',
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='date_commande',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='date_livraison',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Livraison'),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='En cours', max_length=20, verbose_name='Statut de la Commande'),
        ),
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gstock.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='lignecommandeclient',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='unitemesure',
            name='libele',
            field=models.CharField(max_length=100, verbose_name='Libéllé '),
        ),
    ]
