# Generated by Django 4.2.6 on 2023-11-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstock', '0004_alter_produit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='cout_achat',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='date_peremption',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='groupe_taxe',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='niveau_alerte_stock',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='unite_mesure',
        ),
    ]
