# Generated by Django 4.2.6 on 2023-11-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_categorie_alter_contact_type'),
        ('gstock', '0005_remove_produit_cout_achat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now_add=True, verbose_name='Date de Commande')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name_plural': 'Commandes Fournisseurs',
            },
        ),
        migrations.RemoveField(
            model_name='familleproduit',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='produit',
            name='cout_achat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Coût d'Achat"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='date_peremption',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Péremption'),
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Fournisseur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='groupe_taxe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gstock.groupetaxe', verbose_name='Groupe de Taxes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='niveau_alerte_stock',
            field=models.PositiveIntegerField(default=2, verbose_name="Niveau d'Alerte de Stock"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Prix'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(default=50, verbose_name='Quantité en Stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_mesure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gstock.unitemesure', verbose_name='Unité de Mesure'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Unitaire')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.commandefournisseur', verbose_name='Commande Fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name_plural': 'Lignes de Commande',
            },
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='produits',
            field=models.ManyToManyField(through='gstock.LigneCommande', to='gstock.produit', verbose_name='Produits'),
        ),
    ]
