# Generated by Django 4.2.6 on 2023-11-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstock', '0006_commandefournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefournisseur',
            name='date_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date de reception'),
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='reference',
            field=models.CharField(default=1, max_length=100, verbose_name='Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut de la Commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant TTC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='date_commande',
            field=models.DateField(verbose_name='Date de Commande'),
        ),
    ]
