# Generated by Django 4.2.6 on 2023-11-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstock', '0007_commandefournisseur_date_reception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandefournisseur',
            name='date_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Réception'),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut de la Commande'),
        ),
    ]
