# Generated by Django 4.2.6 on 2023-11-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_categorie_alter_contact_type'),
        ('gstock', '0008_alter_commandefournisseur_date_reception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(limit_choices_to={'categorie': 'Fournisseur'}, on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Fournisseur'),
        ),
    ]
