# Generated by Django 4.2.6 on 2023-12-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_categorie_alter_contact_type'),
        ('gstock', '0009_alter_produit_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(verbose_name='Date de Commande')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('livree', 'Livré'), ('annulee', 'Annulée')], default='En cours', max_length=20, verbose_name='Statut de la Commande')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date de Réception')),
                ('client', models.ForeignKey(limit_choices_to={'categorie': 'Client'}, on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Client')),
            ],
            options={
                'verbose_name_plural': 'Commandes Clients',
            },
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='fournisseur',
            field=models.ForeignKey(limit_choices_to={'categorie': 'Fournisseur'}, on_delete=django.db.models.deletion.CASCADE, to='contact.contact', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='En cours', max_length=20, verbose_name='Statut de la Commande'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.familleproduit', verbose_name='Famille'),
        ),
        migrations.CreateModel(
            name='LigneCommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('commande_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.commandeclient', verbose_name='Commande Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gstock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name_plural': 'Lignes de commande client',
            },
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='produits',
            field=models.ManyToManyField(through='gstock.LigneCommandeClient', to='gstock.produit', verbose_name='Produits'),
        ),
    ]
