# Generated by Django 4.2.6 on 2023-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='categorie',
            field=models.CharField(choices=[('Client', 'Client'), ('Prospect', 'Prospect'), ('Fournisseur', 'Fournisseur')], default='Clien', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Societe', 'Société'), ('Particulier', 'Particulier')], default='Societe', max_length=20, verbose_name='Type'),
        ),
    ]
