# Generated by Django 4.2.6 on 2023-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_categorie_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='categorie',
            field=models.CharField(choices=[('Client', 'Client'), ('Prospect', 'Prospect'), ('Fournisseur', 'Fournisseur')], max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Societe', 'Société'), ('Particulier', 'Particulier')], max_length=20, verbose_name='Type'),
        ),
    ]
