# Generated by Django 4.2.6 on 2023-11-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usercompte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(related_name='users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(related_name='users', to='auth.permission'),
        ),
    ]
