# Generated by Django 4.2.6 on 2023-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercompte', '0003_alter_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
