# Generated by Django 4.2.6 on 2023-11-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usercompte', '0004_utilisateur_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='Visiteur',
        ),
    ]
