# Generated by Django 4.2.6 on 2023-11-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usercompte', '0005_rename_utilisateur_visiteur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visiteur',
            new_name='Utilisateur',
        ),
    ]
