# Generated by Django 4.2.6 on 2023-11-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercompte', '0006_rename_visiteur_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
